name: painter_from_svg
description: "A Flutter CLI for generating icon files based on CustomPainter for `.svg` files."
version: 0.0.2
homepage: https://github.com/mscherry14/painter_from_svg

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  args: ^2.7.0
  code_builder: ^4.10.1
  dart_style: ^3.1.0
  flutter:
    sdk: flutter
  glob: ^2.1.3
  path: ^1.9.1
  xml: ^6.5.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

executables:
  generate_icons: generate_icons
